### ISSUE TITLE
Default camera resolution maxes out CPUs

### ISSUE THREAD

**Issue by BotBitz** [qcr/PenguinPi-robot#4]
When running at 1640 x 1232 camera resolution ppweb.py maxes out all 4 cores of the Rpi3B+. 

Proposed solution is to reduce the stock camera resolution for the script to 640 x 480 resulting much lower CPU usage. See below. 
![image](https://github.com/qcr/PenguinPi-robot/assets/6804250/a81e3777-ebab-4ecf-941f-06e95e4b0ab2)

**Comment by Tobias-Fischer** [comment]
Hi @BotBitz - I tried 640x480 at first. However, this resulted in a cropped image that did not show the full field of view. I think this needs a bit of playing around with the new picamera2 library to properly get sorted out. Agreed though that we should reduce the resolution to save CPU.

**Comment by Tobias-Fischer** [comment]
Relevant:
- https://github.com/raspberrypi/picamera2/issues/450
- https://github.com/raspberrypi/picamera2/discussions/585
- `ScalerCrop` in https://datasheets.raspberrypi.com/camera/picamera2-manual.pdf

**Comment by BotBitz** [comment]
Agreed. I made some quick patches to see what I could get going and it
looked cropped but haven’t had enough time to play yet. Will get a PR once
I have something working.

**Comment by Tobias-Fischer** [comment]
Fixed in #5
